# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CFG.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1123, 656)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/LZH/Pictures/Saved Pictures/56868f0ab9c7a108edfb3c07060155f2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    color:black;\n"
"    background-color:;\n"
"    border-radius:6px;\n"
"    border:1px solid rgb black\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:#CCEEFF;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:#CCEEFF;\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"QMainWindow {\n"
"    background-color:;\n"
"}\n"
"QMessageBox{\n"
"    font-size:16px;\n"
"    line-height:30px\n"
"}\n"
"QTabWidget{\n"
"    font-family:Microsoft Yahei;\n"
"    color:black;\n"
"    border:1px solid rgb black\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border:1px solid rgb black\n"
"}\n"
"\n"
"QLabel{\n"
"    font-family:Microsoft Yahei;\n"
"    color:black;\n"
"}\n"
"QGroupBox{\n"
"    font-family:Microsoft Yahei;\n"
"    color:black;\n"
"}\n"
"QTextEdit{\n"
"    color:black;\n"
"    font-size:16px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 441, 601))
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setObjectName("groupBox")
        self.grammar = QtWidgets.QTextEdit(self.groupBox)
        self.grammar.setGeometry(QtCore.QRect(10, 170, 421, 421))
        self.grammar.setFrameShape(QtWidgets.QFrame.Box)
        self.grammar.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.grammar.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.grammar.setReadOnly(False)
        self.grammar.setPlaceholderText("")
        self.grammar.setObjectName("grammar")
        self.open = QtWidgets.QPushButton(self.groupBox)
        self.open.setGeometry(QtCore.QRect(10, 30, 201, 41))
        self.open.setObjectName("open")
        self.save = QtWidgets.QPushButton(self.groupBox)
        self.save.setGeometry(QtCore.QRect(230, 30, 201, 41))
        self.save.setObjectName("save")
        self.show_vn = QtWidgets.QLineEdit(self.groupBox)
        self.show_vn.setGeometry(QtCore.QRect(50, 90, 161, 31))
        self.show_vn.setInputMask("")
        self.show_vn.setFrame(False)
        self.show_vn.setAlignment(QtCore.Qt.AlignCenter)
        self.show_vn.setObjectName("show_vn")
        self.show_vt = QtWidgets.QLineEdit(self.groupBox)
        self.show_vt.setGeometry(QtCore.QRect(270, 90, 161, 31))
        self.show_vt.setText("")
        self.show_vt.setFrame(False)
        self.show_vt.setAlignment(QtCore.Qt.AlignCenter)
        self.show_vt.setObjectName("show_vt")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 90, 31, 31))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(230, 90, 31, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(320, 130, 71, 31))
        self.label_3.setObjectName("label_3")
        self.start = QtWidgets.QLineEdit(self.groupBox)
        self.start.setGeometry(QtCore.QRect(400, 130, 31, 31))
        self.start.setFrame(False)
        self.start.setAlignment(QtCore.Qt.AlignCenter)
        self.start.setObjectName("start")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 72, 31))
        self.label_4.setObjectName("label_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(450, 30, 661, 601))
        self.groupBox_2.setObjectName("groupBox_2")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_2)
        self.tabWidget.setGeometry(QtCore.QRect(0, 90, 661, 511))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.Simplify_cfg = QtWidgets.QWidget()
        self.Simplify_cfg.setObjectName("Simplify_cfg")
        self.simplify_cfg_result = QtWidgets.QTextEdit(self.Simplify_cfg)
        self.simplify_cfg_result.setGeometry(QtCore.QRect(10, 10, 631, 461))
        self.simplify_cfg_result.setFrameShape(QtWidgets.QFrame.Box)
        self.simplify_cfg_result.setReadOnly(True)
        self.simplify_cfg_result.setPlaceholderText("")
        self.simplify_cfg_result.setObjectName("simplify_cfg_result")
        self.tabWidget.addTab(self.Simplify_cfg, "")
        self.Left_common_factor = QtWidgets.QWidget()
        self.Left_common_factor.setObjectName("Left_common_factor")
        self.left_common_factor_result = QtWidgets.QTextEdit(self.Left_common_factor)
        self.left_common_factor_result.setGeometry(QtCore.QRect(10, 10, 631, 461))
        self.left_common_factor_result.setFrameShape(QtWidgets.QFrame.Box)
        self.left_common_factor_result.setReadOnly(True)
        self.left_common_factor_result.setObjectName("left_common_factor_result")
        self.tabWidget.addTab(self.Left_common_factor, "")
        self.Left_recursion = QtWidgets.QWidget()
        self.Left_recursion.setObjectName("Left_recursion")
        self.left_recursion_result = QtWidgets.QTextEdit(self.Left_recursion)
        self.left_recursion_result.setGeometry(QtCore.QRect(10, 10, 631, 461))
        self.left_recursion_result.setFrameShape(QtWidgets.QFrame.Box)
        self.left_recursion_result.setReadOnly(True)
        self.left_recursion_result.setObjectName("left_recursion_result")
        self.tabWidget.addTab(self.Left_recursion, "")
        self.Get_first_follow = QtWidgets.QWidget()
        self.Get_first_follow.setObjectName("Get_first_follow")
        self.first_result = QtWidgets.QTextEdit(self.Get_first_follow)
        self.first_result.setGeometry(QtCore.QRect(10, 50, 301, 421))
        self.first_result.setFrameShape(QtWidgets.QFrame.Box)
        self.first_result.setReadOnly(True)
        self.first_result.setPlaceholderText("")
        self.first_result.setObjectName("first_result")
        self.follow_result = QtWidgets.QTextEdit(self.Get_first_follow)
        self.follow_result.setGeometry(QtCore.QRect(340, 50, 301, 421))
        self.follow_result.setFrameShape(QtWidgets.QFrame.Box)
        self.follow_result.setReadOnly(True)
        self.follow_result.setPlaceholderText("")
        self.follow_result.setObjectName("follow_result")
        self.label_5 = QtWidgets.QLabel(self.Get_first_follow)
        self.label_5.setGeometry(QtCore.QRect(140, 10, 51, 31))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.Get_first_follow)
        self.label_6.setGeometry(QtCore.QRect(460, 10, 61, 31))
        self.label_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.Get_first_follow, "")
        self.FA = QtWidgets.QWidget()
        self.FA.setObjectName("FA")
        self.scrollArea = QtWidgets.QScrollArea(self.FA)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 631, 461))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Box)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 627, 457))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.fa_graph = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fa_graph.setText("")
        self.fa_graph.setObjectName("fa_graph")
        self.gridLayout.addWidget(self.fa_graph, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.FA, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 10, 631, 461))
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.Box)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 627, 457))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dfa_graph = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.dfa_graph.setText("")
        self.dfa_graph.setObjectName("dfa_graph")
        self.gridLayout_2.addWidget(self.dfa_graph, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_3.setGeometry(QtCore.QRect(10, 10, 631, 461))
        self.scrollArea_3.setFrameShape(QtWidgets.QFrame.Box)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 627, 457))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.minidfa_graph = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.minidfa_graph.setText("")
        self.minidfa_graph.setObjectName("minidfa_graph")
        self.gridLayout_3.addWidget(self.minidfa_graph, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.Simplify_cfg_button = QtWidgets.QPushButton(self.groupBox_2)
        self.Simplify_cfg_button.setGeometry(QtCore.QRect(10, 30, 121, 41))
        self.Simplify_cfg_button.setObjectName("Simplify_cfg_button")
        self.Left_common_factor_button = QtWidgets.QPushButton(self.groupBox_2)
        self.Left_common_factor_button.setGeometry(QtCore.QRect(140, 30, 121, 41))
        self.Left_common_factor_button.setObjectName("Left_common_factor_button")
        self.Left_recursion_button = QtWidgets.QPushButton(self.groupBox_2)
        self.Left_recursion_button.setGeometry(QtCore.QRect(270, 30, 121, 41))
        self.Left_recursion_button.setObjectName("Left_recursion_button")
        self.Get_first_follow_button = QtWidgets.QPushButton(self.groupBox_2)
        self.Get_first_follow_button.setGeometry(QtCore.QRect(400, 30, 121, 41))
        self.Get_first_follow_button.setObjectName("Get_first_follow_button")
        self.FA_button = QtWidgets.QPushButton(self.groupBox_2)
        self.FA_button.setGeometry(QtCore.QRect(530, 30, 121, 41))
        self.FA_button.setObjectName("FA_button")
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(1020, 10, 93, 28))
        self.reset.setObjectName("reset")
        self.cfg_create = QtWidgets.QPushButton(self.centralwidget)
        self.cfg_create.setGeometry(QtCore.QRect(360, 10, 91, 28))
        self.cfg_create.setObjectName("cfg_create")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(120, 10, 271, 31))
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.Simplify_cfg_button.clicked.connect(MainWindow.Simplify_cfg_button_clicked)
        self.Left_common_factor_button.clicked.connect(MainWindow.Left_common_factor_button_clicked)
        self.Left_recursion_button.clicked.connect(MainWindow.Left_recursion_button_clicked)
        self.Get_first_follow_button.clicked.connect(MainWindow.Get_first_follow_button_clicked)
        self.FA_button.clicked.connect(MainWindow.FA_button_clicked)
        self.open.clicked.connect(MainWindow.open_clicked)
        self.save.clicked.connect(MainWindow.save_clicked)
        self.reset.clicked.connect(MainWindow.reset_clicked)
        self.cfg_create.clicked.connect(MainWindow.cfg_initial)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "文法问题处理器"))
        self.groupBox.setTitle(_translate("MainWindow", "查看文法"))
        self.open.setText(_translate("MainWindow", "打开"))
        self.save.setText(_translate("MainWindow", "保存"))
        self.show_vn.setPlaceholderText(_translate("MainWindow", "非终结符集合"))
        self.show_vt.setPlaceholderText(_translate("MainWindow", "终结符集合"))
        self.label.setText(_translate("MainWindow", "vn"))
        self.label_2.setText(_translate("MainWindow", "vt"))
        self.label_3.setText(_translate("MainWindow", "开始符号"))
        self.label_4.setText(_translate("MainWindow", "产生式："))
        self.groupBox_2.setTitle(_translate("MainWindow", "文法处理"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Simplify_cfg), _translate("MainWindow", "化简"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Left_common_factor), _translate("MainWindow", "左公因子"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Left_recursion), _translate("MainWindow", "左递归"))
        self.label_5.setText(_translate("MainWindow", "fisrt"))
        self.label_6.setText(_translate("MainWindow", "follow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Get_first_follow), _translate("MainWindow", "查看first与follow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FA), _translate("MainWindow", "有穷自动机"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "dfa"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "最小化dfa"))
        self.Simplify_cfg_button.setText(_translate("MainWindow", "化简文法"))
        self.Left_common_factor_button.setText(_translate("MainWindow", "消除左公共因子"))
        self.Left_recursion_button.setText(_translate("MainWindow", "消除左递归"))
        self.Get_first_follow_button.setText(_translate("MainWindow", "first与follow"))
        self.FA_button.setText(_translate("MainWindow", "有穷自动机"))
        self.reset.setText(_translate("MainWindow", "重置"))
        self.cfg_create.setText(_translate("MainWindow", "初始化"))
        self.label_7.setText(_translate("MainWindow", "文法写入完成后请点击“初始化”:"))
