# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'processline.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(751, 846)
        MainWindow.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"QMessageBox{\n"
"    font-size:16px;\n"
"    line-height:30px\n"
"}        ")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.get_str = QtWidgets.QGroupBox(self.centralwidget)
        self.get_str.setGeometry(QtCore.QRect(20, 10, 711, 121))
        self.get_str.setObjectName("get_str")
        self.lineEdit = QtWidgets.QLineEdit(self.get_str)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 571, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.generate = QtWidgets.QPushButton(self.get_str)
        self.generate.setGeometry(QtCore.QRect(590, 30, 111, 31))
        self.generate.setObjectName("generate")
        self.open = QtWidgets.QPushButton(self.get_str)
        self.open.setGeometry(QtCore.QRect(10, 70, 341, 41))
        self.open.setObjectName("open")
        self.save = QtWidgets.QPushButton(self.get_str)
        self.save.setGeometry(QtCore.QRect(360, 70, 341, 41))
        self.save.setObjectName("save")
        self.table_graph = QtWidgets.QGroupBox(self.centralwidget)
        self.table_graph.setGeometry(QtCore.QRect(20, 140, 711, 681))
        self.table_graph.setObjectName("table_graph")
        self.tabWidget = QtWidgets.QTabWidget(self.table_graph)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 691, 641))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.nfa_tab = QtWidgets.QWidget()
        self.nfa_tab.setObjectName("nfa_tab")
        self.scrollArea = QtWidgets.QScrollArea(self.nfa_tab)
        self.scrollArea.setGeometry(QtCore.QRect(10, 300, 661, 301))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 659, 299))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.nfa_graph = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.nfa_graph.setText("")
        self.nfa_graph.setObjectName("nfa_graph")
        self.gridLayout.addWidget(self.nfa_graph, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.nfa_table = QtWidgets.QTableWidget(self.nfa_tab)
        self.nfa_table.setGeometry(QtCore.QRect(10, 10, 661, 281))
        self.nfa_table.setObjectName("nfa_table")
        self.nfa_table.setColumnCount(0)
        self.nfa_table.setRowCount(0)
        self.tabWidget.addTab(self.nfa_tab, "")
        self.dfa_tab = QtWidgets.QWidget()
        self.dfa_tab.setObjectName("dfa_tab")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.dfa_tab)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 300, 661, 301))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 659, 299))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dfa_graph = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.dfa_graph.setText("")
        self.dfa_graph.setObjectName("dfa_graph")
        self.gridLayout_2.addWidget(self.dfa_graph, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.dfa_table = QtWidgets.QTableWidget(self.dfa_tab)
        self.dfa_table.setGeometry(QtCore.QRect(10, 10, 661, 281))
        self.dfa_table.setObjectName("dfa_table")
        self.dfa_table.setColumnCount(0)
        self.dfa_table.setRowCount(0)
        self.tabWidget.addTab(self.dfa_tab, "")
        self.minidfa_tab = QtWidgets.QWidget()
        self.minidfa_tab.setObjectName("minidfa_tab")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.minidfa_tab)
        self.scrollArea_3.setGeometry(QtCore.QRect(10, 300, 661, 301))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 659, 299))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.minidfa_graph = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.minidfa_graph.setText("")
        self.minidfa_graph.setObjectName("minidfa_graph")
        self.gridLayout_3.addWidget(self.minidfa_graph, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.minidfa_table = QtWidgets.QTableWidget(self.minidfa_tab)
        self.minidfa_table.setGeometry(QtCore.QRect(10, 10, 661, 281))
        self.minidfa_table.setObjectName("minidfa_table")
        self.minidfa_table.setColumnCount(0)
        self.minidfa_table.setRowCount(0)
        self.tabWidget.addTab(self.minidfa_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.generate.clicked.connect(MainWindow.generate_clicked)
        self.save.clicked.connect(MainWindow.save_clicked)
        self.open.clicked.connect(MainWindow.open_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.get_str.setTitle(_translate("MainWindow", "获取正则表达式"))
        self.generate.setText(_translate("MainWindow", "生成自动机"))
        self.open.setText(_translate("MainWindow", "打开"))
        self.save.setText(_translate("MainWindow", "保存"))
        self.table_graph.setTitle(_translate("MainWindow", "展示图表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.nfa_tab), _translate("MainWindow", "NFA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dfa_tab), _translate("MainWindow", "DFA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.minidfa_tab), _translate("MainWindow", "最小化DFA"))
